# Generated by Django 4.0.4 on 2022-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=13)),
                ('site', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
